# Generated by Django 4.1.3 on 2022-12-06 17:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clinic', '0002_backtext2stl_backtextstl_dentist_doctor1stl_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Back2',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('image', models.ImageField(upload_to='')),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('updated_date', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.DeleteModel(
            name='Doctor2',
        ),
        migrations.DeleteModel(
            name='Doctor2STL',
        ),
    ]
