# Generated by Django 4.1.3 on 2022-12-06 18:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('clinic', '0005_state_delete_backtext2stl_delete_backtextstl'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='state',
            name='image',
        ),
    ]
