# Generated by Django 4.1.3 on 2022-12-08 02:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('clinic', '0008_bodroststl'),
    ]

    operations = [
        migrations.DeleteModel(
            name='PostsSTL',
        ),
    ]
