# Generated by Django 4.1.3 on 2022-12-10 18:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('clinic', '0012_backtext2h_bodrosth_doctor1h_newsh_posts2h_postsh_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='BodrostH',
        ),
        migrations.DeleteModel(
            name='BodrostSTL',
        ),
    ]
