# Generated by Django 4.1.3 on 2022-12-13 17:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('clinic', '0018_service2'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Service2',
        ),
    ]
