# Generated by Django 4.1.3 on 2022-12-20 16:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('clinic', '0019_delete_service2'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Bodrost',
        ),
        migrations.DeleteModel(
            name='Help',
        ),
    ]
