# Generated by Django 4.1.3 on 2022-12-20 16:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clinic', '0020_delete_bodrost_delete_help'),
    ]

    operations = [
        migrations.CreateModel(
            name='HelpU',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, null=True)),
                ('phone', models.IntegerField(null=True)),
                ('description', models.TextField()),
            ],
        ),
    ]
